function [fitresult, gof,a,b] = createFit(SeqBlocks)
%CREATEFIT(SEQBLOCKS)
%  Create a fit.
%
%  Data for 'Exponential Fit' fit:
%      Y Output: SeqBlocks
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Aug-2017 14:40:28


%% Fit: 'Exponential Fit'.
[xData, yData] = prepareCurveData( [], SeqBlocks );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.445651295214594 -0.0565738820778423];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Exponential Fit' );
h = plot( fitresult, xData, yData );
legend( h, 'Sequence RTs', 'Exponential Fit', 'Location', 'NorthEast' );
% Label axes
ylabel RT
grid on


